In [3]:
import numpy as np

# We create a 4 x 5 ndarray that contains integers from 0 to 19

X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X

#indices = np.array([1,3])

indices = [1,3]

# We print X

print()

print('X = \n', X)

print()

# We print indices

print('indices = ', indices)

print()

# We use the indices ndarray to select the 2nd and 4th row of X

Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X

Z = X[:, indices]

# We print Y

print()

print('Y = \n', Y)

# We print Z

print()

print('Z = \n', Z, '\n')

Z[0,0]=100

print (X)
print (Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1, 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[100   3]
 [  6   8]
 [ 11  13]
 [ 16  18]]
